"use strict";

import React from 'react';
import ReactDOM from 'react-dom';

const element = (
	<div className="row">
		<div className="col-sm-6">
			<h2>Generated by React</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p><a className="btn btn-primary" href="#" role="button">View details ?</a></p>
		</div>
		<div className="col-sm-6">
			<h2>React Paragraph 2</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p><a className="btn btn-primary" href="#" role="button">View details ?</a></p>
		</div>
	</div>
)
  
ReactDOM.render (
  element,
  document.getElementById('reactdemo')
)


